# Menu
menu:
  Home: /
  About: /about
  Archives: /archives
  Life: /tags/Life/
  Chilly: /chilly
rss: /atom.xml

# sidebar:
#   display: always # 可选值: post, always, hide, remove
#   avatar:
#     url: /images/avatar.gif # 头像资源路径
#     rounded: false # 如果为 true, 头像将会显示为圆形
#     opacity: 1 # 头像透明度，取值从0到1,1表示完全不透明

# social:
#   GitHub: https://github.com/yourname || github
#   E-Mail: mailto:yourname@gmail.com || envelope

# Miscellaneous
favicon: /favicon.ico
brand: /images/hexo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/hexo-inverted.svg

# Content
excerpt_link: Read More...
# excerpt_description: false  # 是否在摘录下方显示文章描述
# read_more_btn: false        # 是否显示阅读全文按钮

# MIIT ICP/IP/DOMAIN
beian:
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Tags
show_count: true

# Toc
toc: true


# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'